### ISSUE TITLE
Update Game List

### ISSUE THREAD

**Issue by andreluizgit** [cemu-project/Cemu#100]
Even after add BOTW folder the Cemu won't update game list (it works in stable version).

**Comment by Crementif** [comment]
Can you please provide more info about what format your game files are in, what OS you use and where you store your Cemu files.

**Comment by Squall-Leonhart** [comment]
sounds like a dump missing the meta file.

**Comment by danir-de** [comment]
I'm having the same problem.

Using Manjaro (Arch based), compiled from source, Breath of the Wild won't get listed in the game list - even though it's being shown when starting in 1.16.2f (in Wine).

On my part it seems to be related to the game dump being merged with an update (shows red in game list).
The Tooltip even states that the game might stop working with a future update, so that's that.

Gonna stay on 1.26.2f even though it breaks my heart.

**Comment by Crementif** [comment]
I have noticed bug where the initial setup won't read updates or DLC if it uses a previously created MLC folder until you reboot Cemu. Probably unrelated but it might help.

**Comment by danir-de** [comment]
Have thought of that as well, but nothing changes when restarting.
When launching via console, there isn't any relevant log either.

Is there a way to generate a log about what is happening on startup / game launch (when selecting the rpx file manually) ?

**Comment by Squall-Leonhart** [comment]
> On my part it seems to be related to the game dump being merged with an update (shows red in game list).

This is the case, it will not be fixed afaik, get a clean correct dump.
