### ISSUE TITLE
[Feature request] Supporting the motion controls of Dualshock 3

### ISSUE THREAD

**Issue by vivi3107** [cemu-project/Cemu#1044]
The motion controls of my Dualshock 3 only work in Cemu when:

- I use ScpToolkit
- I use DSUController API
- I use Cemu 1.27.1 (or older) with Cemuhook installed
- I check this option

![a](https://github.com/cemu-project/Cemu/assets/44928480/d76bd378-009d-4bbb-ac10-8f0534b961c4)

Perhaps it would be possible to implement this in a newer version of Cemu so I don't have to switch between older and newer versions.

**Comment by vivi3107** [comment]
I know, but the motion control won't work if I don't check the option visible in the picture I provided. It has to be set to "DSU1: [...]", not "Default". This option is only available if Cemuhook is installed.

**Comment by vivi3107** [comment]
> Did you click `Settings` -> `Use motion` ![image](https://private-user-images.githubusercontent.com/125745866/290854749-43b0f546-2386-41ad-b694-2f7d9946c97a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTQyMDYsIm5iZiI6MTcwMjY1MzkwNiwicGF0aCI6Ii8xMjU3NDU4NjYvMjkwODU0NzQ5LTQzYjBmNTQ2LTIzODYtNDFhZC1iNjk0LTJmN2Q5OTQ2Yzk3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxNTI1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2Y1ZGJmZGZiODUyYThjZmExODk0MWIzYWY5MjlhMWIzNjZhN2U4MGY4NjU0N2VmZDYwNWFlZTI0NGMyYmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oYjX2OveOqzsU4ZY7K2gTUXVSNVFjUQQXU0-SLw_p6Y)

yes

**Comment by Exzap** [comment]
On modern Cemu (as of writing the version is 2.0-68) you should be able to use a DS3 controller directly with either of these two methods:
- Setting the controller API to SDL and choosing the controller in the drop down. It's important that you then **don't use ScpToolkit** in combination with SDL. Otherwise the controller wont show up for SDL. You might also have to uninstall any drivers installed by ScpToolkit.
- If you do want to keep using ScpToolkit, then you can select DSU API in Cemu and configure it similar to how you did for the old Cemuhook method. This replicates your original setup via Cemuhook. The "GamePad motion source" menu is replaced by the "Use motion" checkbox, see capitalistspz' post above.

To clarify, in both cases you need to click the settings button on the controller configuration panel and tick `Use motion`.

If neither of this works then please come to the discord or subreddit for troubleshooting. But generally what you are asking for is already supported by Cemu
