### ISSUE TITLE
[Feature-Request (Windows)] Make Installer

### ISSUE THREAD

**Issue by FennekFox19** [cemu-project/Cemu#1052]
the creation of a setup.exe would greatly improove the setup process, because it could load a troubleshooter during the installation that scans if your device can fulfill the bacic requirements and inform you if it is qualified or ask if you want to continue te setup despite being not able to run well because of not fulfilling one or more of the technical requirements of Cemu.

It would Improove cemu drastically in terms of less issues of people who do not fulfill the basic requirements.

**Comment by Exzap** [comment]
This isn't planned for now. There may be some value in having a simple installer but it's just another thing that we'd have to maintain and the benefit is too small for that. It also doesn't play well with Cemu being a portable application on Windows currently.

Regarding the requirements check: The line of what the minimum requirements are is kinda blurry and depends on which game is being played so it's difficult to check for it. But I do agree with the sentiment that Cemu should have helpful error messages instead of just showing black screens or crashing to desktop.
