### ISSUE TITLE
[Bug] WUA compression in title manager does nothing

### ISSUE THREAD

**Issue by rehtlaw** [cemu-project/Cemu#1105]
### Current Behavior

Confirming the wua compression dialog, only a short progress bar is shown that quickly disappears with no new file being created.
I only tested this with a Splatoon Gamedump + Update. The game runs just fine when booting the files I'm trying to compress.

### Expected Behavior

For a .wua file to be created with both the game and update files inside.

### Steps to Reproduce

(AppImage and Windows version through wine of 2.0-66 were tested)
- Open title manager
- Select a game that's stored as a folder
- Select "Convert to compressed Wii U archive (.wua)"

**Comment by bezza191** [comment]
Im having the same issue, but specifically with Yoshi's Woolly World

**Comment by mundodisco-argentina** [comment]
I add more information on this subject: the compression / conversion into WUA stopped working in version 2.0-55 and up. Versions 2.0-52, 2.0-53 and 2.0-54 work fine. Prior versions (2.0-51 and below) do not show games in "folder format" downloaded with latest WiiUDownloader (v2.30), so I cannot test the WUA part. But be sure something in the code "broke" since version 2.0-55.

**Comment by mundodisco-argentina** [comment]
> ### Current Behavior
> Confirming the wua compression dialog, only a short progress bar is shown that quickly disappears with no new file being created. I only tested this with a Splatoon Gamedump + Update. The game runs just fine when booting the files I'm trying to compress.
> 
> ### Expected Behavior
> For a .wua file to be created with both the game and update files inside.
> 
> ### Steps to Reproduce
> (AppImage and Windows version through wine of 2.0-66 were tested)
> 
> * Open title manager
> * Select a game that's stored as a folder
> * Select "Convert to compressed Wii U archive (.wua)"

@rehtlaw, please test WUA conversion with CEMU 2.0-54 (just download it in another folder and copy "keys.txt" from the other one). I have tested every single preliminar CEMU version and the error happens since release 2.0-55 onwards.

**Comment by mundodisco-argentina** [comment]
However... despite releases 2.0-52, 2.0-53 and 2.0-54 doing the WUA conversion, I have detected two anormal things: 1) the estimated size during conversion progress is not reached (I mean, it makes a big jump near the latest megabytes) AND 2) those WUA files make CEMU emulator crash when trying to open the game. Interestingly enough, this happens when the game was downloaded with updates and DLC's. If you try to convert a base game (without the other folders), the conversion progression runs smoothly (no megabytes "jump" at the end). And game loads just fine under CEMU (tested by myself with New Super Mario Bros U and Super Mario Maker).

**Comment by rehtlaw** [comment]
> > ### Current Behavior
> > Confirming the wua compression dialog, only a short progress bar is shown that quickly disappears with no new file being created. I only tested this with a Splatoon Gamedump + Update. The game runs just fine when booting the files I'm trying to compress.
> > ### Expected Behavior
> > For a .wua file to be created with both the game and update files inside.
> > ### Steps to Reproduce
> > (AppImage and Windows version through wine of 2.0-66 were tested)
> > 
> > * Open title manager
> > * Select a game that's stored as a folder
> > * Select "Convert to compressed Wii U archive (.wua)"
> 
> @rehtlaw, please test WUA conversion with CEMU 2.0-54 (just download it in another folder and copy "keys.txt" from the other one). I have tested every single preliminar CEMU version and the error happens since release 2.0-55 onwards.

yup can confirm, 2.0-54 can create the archive, but trying to run it crashes the emulator.

**Comment by mundodisco-argentina** [comment]
@rehtlaw So... Have you evee been able to create a working WUA file? If so, with which software / version? And did you use a game in "folder format" as source? I could never do it... In old Cemu releases (prior to 2.0-52), I cannot make Cemu to detect games in folder format. With Cemu 2.0-52 up to 2.0-54, conversion starts but resulting file is corrupted. And with Cemu after 2.0-55, conversion never starts. And I don't know any other software to make WUA files...do you?

**Comment by rehtlaw** [comment]
All my existing .wua files have been created on older versions of 2.0 using games in the folder format.
I just tried compressing my copy of Splatoon with the original 2.0 release for Windows and the resulting .wua file works perfectly fine, but I do remember compressing other games that were in the same format with later versions too, but I've done that a while back already.

**Comment by rehtlaw** [comment]
OK I just did some testing:
2.0-52 is the first version that creates broken .wua archives. It's also the first version that seems to recognize gamefolders as both folders and NUS. It doesn't matter if I select the folder or the NUS entry in the title manager, both result in a bad .wua archive.

**Comment by mundodisco-argentina** [comment]
@rehtlaw I think I cannot understand your statement: "It's also the first version that seems to recognize gamefolders as both folders and NUS." What do you mean by NUS entries?   And, when you mean "game folders", you refer to the folders created by WiiUDownloader, those named (for example): "New SUPER MARIO BROS U [DLC] [0005000c10101d00]", "New SUPER MARIO BROS U [Game] [0005000010101d00]", "New SUPER MARIO BROS U [Update] [0005000e10101d00]", and the three of them with several *.app and *.h3 files, "title.cert", "title.tik" and "title.tmd", right?    Because I've seen on Internet an (older?) format of game folders with "code", "content", "meta" subfolders, and "*.rpx" files. Well, you say you could convert working WUA files with the first 2.0 releases of CEMU, but I cannot make those CEMU versions detect ("see") my Wii U games in "folder" format (meaning, the one with "title.tmd" and so).

**Comment by Exzap** [comment]
I had to delete some comments as they mentioned a piracy tool.

I tried creating a wua file from a NUS (.app) dump just now on 2.0-66 and that worked for me and created a functioning wua file. That said, NUS to wua conversion is not very well tested so there may indeed be bugs somewhere.

The mentioned 2.0-52 release added support for game titles in NUS (.app) format, see #981. What I could see happening is that Cemu detects an incomplete or broken NUS dump in your game folder now whereas the older versions would ignore it and always use the folder dump. 

Also this isn't obvious but it doesn't matter which type (WUD or game folder) of the title you right click in the title manager for conversion. Cemu will always try to be smart about which titles to source from and currently the only way to guarantee it's not using the NUS title for wua conversion is by removing it from the game folder. So maybe try that and see if that helps?

**Comment by rehtlaw** [comment]
Yup, all the .app files were still inside the folders. After deleting them all from both the base game and update, it compressed the game without problems and also resulted in a functioning archive.

**Comment by mundodisco-argentina** [comment]
@Exzap when you say you tried vith version 2.0-67, is it because you made some changes in the code? If that is the case, you confirm then that this feature (wua conversion) was not working right, don't you?

And @rehtlaw what do you mean with "after removing all *.app files"? Did you delete all *.app files from your games folders (leaving just *.h3 and title.* files??) So, *.app files are not useful?? Why are there, then? I think I am confused...

**Comment by rehtlaw** [comment]
the .app files were still there right next to the `content`, `code` etc. folders from the conversion process from NUS to a regular folder structure, and because they were still there, the wua compression failed.

**Comment by mundodisco-argentina** [comment]
Ok @rehtlaw , I think I understood now. Your source games are in code/content/meta folders format. However, mine games, all got with a "piracy app" which I won't name ;-) are in NUS folder format (.app, .h3, title.x files inside). In my case, I cannot delete .app files!

**Comment by aeithales** [comment]
> > ### Comportamento Atual
> > Confirmando a caixa de diálogo de compactação wua, apenas uma pequena barra de progresso é mostrada e desaparece rapidamente sem que nenhum novo arquivo seja criado. Eu só testei isso com um Splatoon Gamedump + Update. O jogo funciona perfeitamente ao inicializar os arquivos que estou tentando compactar.
> > ### Comportamento esperado
> > Para que um arquivo .wua seja criado com o jogo e os arquivos de atualização dentro dele.
> > ### Passos para reproduzir
> > (AppImage e versão Windows através do wine de 2.0-66 foram testados)
> > 
> > * Abra o gerenciador de títulos
> > * Selecione um jogo armazenado como uma pasta
> > * Selecione "Converter para arquivo compactado do Wii U (.wua)"
> 
> @rehtlaw, teste a conversão WUA com CEMU 2.0-54 (basta baixá-lo em outra pasta e copiar "keys.txt" da outra). Testei todas as versões preliminares do CEMU e o erro ocorre desde a versão 2.0-55 em diante.

thank you, last version not doing nothing, i'm losing 30min trying fix it

**Comment by dmchmk** [comment]
Hi! Unfortunately, facing this issue on 2.2 version, compiled Sep 8, 2024:( (NixOS, AppImage)

Single-directory games export correctly, but games with updates and dlcs fail(
