### ISSUE TITLE
Matrix community?

### ISSUE THREAD

**Issue by uranuspucksaxophone** [cemu-project/Cemu#113]
Now that Cemu is open-source (thank you!), I would like to humbly suggest to use Matrix.org as an open-source alternative to Discord, it has much more features than IRC, however, thanks to bridging, we don't have to lock ourselves on one platform, we can have an IRC, Matrix and Discord all bridged together, and let users join their preferred platform while being able to contact users on other platforms (like Discord).

**Comment by Tatsh** [comment]
Why not just IRC on freenode?

**Comment by Tatsh** [comment]
I am not really opposed but personally I get annoyed at having so many chat clients open. It used to be every project was on Freenode, or now, Liberachat.

**Comment by n0toose** [comment]
You can host a channel on Libera/OFTC and then access it with Matrix clients, while utilizing the full set of Matrix's features and also allowing for more space in case some other communication protocol pops up in like 5 years or so. I did that with e.g. https://matrix.to/#/#haiku:matrix.org and some people struggled to tell that the "main" channel (and other similar channels) was actually an IRC channel.

**Comment by n0toose** [comment]
The problem about bridging to Discord is that there are also sets of people (that are more developer/nerd-oriented rather than gamer-oriented) that refuse to use it with their "actual" Matrix identities because of concerns regarding data processing.

**Comment by n0toose** [comment]
The part where the feature mismatch between IRC and Matrix becomes evident is when someone decides to paste a picture or do things such as send a sticker.
 
On the IRC side, it's business as usual; you'd have to paste a link to an image anyways, something which the bridge does for you. Some modern clients also show the picture automatically. An example of a project following an IRC <-> Discord approach has to be [ddnet](https://ddnet.tw) and [SuperTuxKart](https://supertuxkart.net), from my experience.

**Comment by Crementif** [comment]
We were indeed planning on doing a Discord bridge but I'm still not sure whether we'll go IRC or Matrix. From an outside perspective it seems that a lot of developers seem to use IRC (more then Matrix from what I can tell), but this might just be a skewed perspective from the few I've seen. Am I correct in that?

I don't really intent on making the bridge more then the few developer channels, and it doesn't have to be very complex. We're fine with self-hosting something and I've already looked into setting up either for a bit. It's really just choosing what's most comfortable for devs.

**Comment by n0toose** [comment]
> From an outside perspective it seems that a lot of developers seem to use IRC (more then Matrix from what I can tell), but this might just be a skewed perspective from the few I've seen. Am I correct in that?

Varies intensely from community to community. There's always a subset of users that use bouncers (or use Matrix like a bouncer, because it is way easier for that purpose) and do not actively chat on, say, a daily/weekly basis. I am not sure if you'll be able to assess what developers will use. Slapping Matrix on top of an OFTC/Libera IRC channel is relatively pretty easy enough. Libera even hosts the stuff required on their own and you can easily join a channel using `#example:libera.chat` (aka. it's already done and some people will join like that, but most will avoid it if it is not explicitly said by the project because they are not actively aware of this), and it's also not that much harder on OFTC, you just have to set the `#example:matrix.org` URL yourself and you are basically done.

**Comment by n0toose** [comment]
For that matter, the easiest way to go would be just bridging a channel between IRC and Discord. The argument that it would be annoying to people that expect their Matrix messages to be deleted if they do so is not valid, as this does not apply from Matrix <-> IRC either, but it might make moderation a bit more complicated.

You also can't kick/ban people on IRC while using Discord, something which is doable on top of the Matrix protocol, because it allows for "virtual users" that are not on Matrix to act as a totally separate user account. With Discord <-> Matrix bridges (where the Matrix channel is bridged on top of IRC), you can kick/ban people on your favorite platform of choice -- from every platform -- apart from IRC. See: https://matrix.org/docs/guides/types-of-bridging#simple-puppeted-bridge

**Comment by Crementif** [comment]
We've now got a Matrix server with a bridge to our two development channels on Discord. I tried IRC but it just felt too limited.

You can visit our matrix server at using https://matrix.to/#/#dev:cemu.info. Please don't use the dev_only if it's not directly talking about code, since we want to avoid a scenario where people post their build issues there.

I tried enabling guest access or preview mode, but it doesn't seem to work unfortunately. I'm pretty sure we have it enabled in the synapse, but it doesn't appear to work. If anyone knows, feel free to help.

**Comment by Crementif** [comment]
Matrix server is now actually working with outside users... After some work the guest access now also kinda works, but only if you join the rooms individually? We have guest access turned on for both the space and the room, so it's weird why it's not working.

Will be limited to just a bridge to the dev channels for now, but I might expand it to the other relevant channels if there's enough interest and it works smoothly.

**Comment by ThisNekoGuy** [comment]
@Crementif I was going to join the Matrix to ask about a crash I just got but I can't seem to join it and the status badge for it claims it's inaccessible:
![Screenshot_20230725_235704](https://github.com/cemu-project/Cemu/assets/28468662/58c37334-70cf-4886-bac3-a229bb6bc903)

**Comment by Crementif** [comment]
Alright, seems like there's a SSL recertification issue. I think it might've been possible to use it through http, but I've now manually renewed it. Feel free to let me know since I may forget about it again. The badge and matrix server work fine now.

**Comment by ThisNekoGuy** [comment]
@Crementif Still can't seem to join, although I can see the rooms now since you renewed the SSL cert
The rooms are reporting 0 people when I attempt to join them and running `/join #cemu:cemu.info` fails too
![Screenshot_20230731_035729](https://github.com/cemu-project/Cemu/assets/28468662/e78746c2-06de-4380-9ca5-e54b03d2dc1b)

**Comment by n0toose** [comment]
Here's my recommendation:
1. Make another Matrix account and give that backup account privileges.
2. Publish a new alias under matrix.org.
3. It will all lead to the same room, but two homeservers will have a way to refer to it.

You can also use other homeservers in order to connect to a known room instead of just using `cemu.info`, which is a single point of failure.

An example from a community that I participate in is: https://matrix.to/#/%23forgejo-development:matrix.org?via=mozilla.org?via=tchncs.de

The URL parameters essentially make the URL so that if there is downtime through matrix.org (or if you just want to distribute the load among multiple servers - if matrix.org were to completely disappear tomorrow then matrix.to would probably also be in a weird state), then just use the URL parameter (the URL parameter will only work if a user from that homeserver is present; Element allows you to share a link like that and includes those parameters by default).

**Comment by Crementif** [comment]
Can anyone try to leave and rejoin the server with Element client to replicate the issue? I don't really wanna lose admin privileges by leaving nor make a new account.

**Comment by ThisNekoGuy** [comment]
No idea why but I just got a notification from my client from the Linux room, so I'm in now
Weird that it just suddenly decided to connect
