### ISSUE TITLE
Cemu Crashes When Opening Mario Maker

### ISSUE THREAD

**Issue by BirdMan8524** [cemu-project/Cemu#1165]
### Current Behavior

As the title suggests, Cemu crashes whenever I open Mario Maker. It works fine on an alternate profile but I want to use my main one for Mario Maker, but I have no idea how to get past the crash.

### Expected Behavior

I expected the game to open like normal on my main profile.

### Steps to Reproduce

All I did was open the game on my main profile. However it works fine on my alternate profile.,

### System Info (Optional)

OS: 
GPU: 

### Logs (Optional)

[log.txt](https://github.com/cemu-project/Cemu/files/14924431/log.txt)
Here's the log file, I don't see what the issue is.

**Comment by Exzap** [comment]
What do you mean by "main profile". Are we talking about accounts or do you have differently configured instances of Cemu setup? Basically to diagnose this further I need to know which setting is making it crash

**Comment by BirdMan8524** [comment]
> What do you mean by "main profile". Are we talking about accounts or do you have differently configured instances of Cemu set up? Basically to diagnose this further I need to know which setting is making it crash

Accounts, I mean accounts

**Comment by Exzap** [comment]
Closing this since the issue is stale and nobody else has reported a similar crash since it was opened. It's likely the crash is due to corrupted game files and the posted log does hint towards that. I recommend redumping the game and update files. If this crash still happens after doing this and updating to latest Cemu then feel free to open a new issue.
