### ISSUE TITLE
connected to pretendo but (online files dumped to cemu)

### ISSUE THREAD

**Issue by qqjonson1234** [cemu-project/Cemu#1233]
### Current Behavior

When playing smm and going to course world this is what it shows:
![Cemu 2 0-61 (experimental) - FPS_ 58 00  Vulkan   Intel GPU   TitleId_ 00050000-1018dc00  Super Mario Maker  US v272  12_28_2023 6_40_29 PM](https://github.com/cemu-project/Cemu/assets/153330504/079d7ebd-c573-4866-b48b-dddee6e2a9ee)
Even though i am connected.

### Expected Behavior

For the game to play as normal

### Steps to Reproduce

Dump files and try to go to course world

### System Info (Optional)

OS: Windows 11 Home 23H2
GPU: Intel(R) Core(TM) i5-8265U
RAM: 8.00 GB

**Comment by Exzap** [comment]
Update Cemu, you are a bit behind and there were some fixes related to online play. Also it seems like you are connecting to Nintendo servers instead of Pretendo? Nintendo servers are down so it's expected to not work.

I will close this since troubleshooting requests should go on Discord or the subreddit.

**Comment by qqjonson1234** [comment]
> Update Cemu, you are a bit behind and there were some fixes related to online play. Also it seems like you are connecting to Nintendo servers instead of Pretendo? Nintendo servers are down so it's expected to not work.
> 
> I will close this since troubleshooting requests should go on Discord or the subreddit.

I have updated it to version 2.3
