### ISSUE TITLE
Skylanders Swap Force breaks with interpreter

### ISSUE THREAD

**Issue by TheRealWario** [cemu-project/Cemu#1285]
### Current Behavior

When running swap force under single-core interpreter, the game will not progress past the title screen. Pressing the A button will not continue to the menus, nor does tapping the screen. You can hear the sound effect for pressing A, but the game will not continue.

### Expected Behavior

Obviously, the game should proceed from the title to the proper menu, with character art and the options to select story mode, battle, or options.

### Steps to Reproduce

use the game profile to select singe-core interpreter, wait for the logos, and attempt to press A on the title.

### System Info (Optional)

OS: Windows 11 23H2
GPU: NVIDIA GeForce GTX 1650
CPU: AMD Ryzen 5 5600H

### Emulation Settings (Optional)

Tried using graphic packs, changing clock speeds, modifying the few other settings in the game profiles, whatever i could. 

### Logs (Optional)

[log.txt](https://github.com/user-attachments/files/16553843/log.txt)

**Comment by Exzap** [comment]
Some games will lock up in interpreter because they prioritize audio and rendering over resource loading, to a degree where the loading thread(s) will get completely CPU starved since the interpreter is so slow. If you open `Debug -> View PPC threads` you can fiddle with the thread priorities there and that usually is enough to get them to progress.

**Comment by TheRealWario** [comment]
Well, that is a very weird quirk to work around. Thanks for the quick response.
