### ISSUE TITLE
Windows / Cemu 2.1- Online files not recognized in Cemu dir

### ISSUE THREAD

**Issue by orcutt989** [cemu-project/Cemu#1331]
### Current Behavior

Cemu 2.1

Running Cemu from C:\Cemu.exe

Copying `otp.bin` and `seeprom.bin` to Cemu dir is not recognized. I found this issue for Linux https://github.com/cemu-project/Cemu/issues/989 and plopped them in `%roaming%\cemu` instead and then they were recognized.

### Expected Behavior

I expect to put otp.bin and seeprom.bin in wherever Cemu.exe is and have them recognized by the program.

### Steps to Reproduce

Install Cemu 2.1
Copy otp.bin and seeprom.bin to location of Cemu.exe
Run Cemu
Go to Options>>General setteings>>Account
See "not setup for online play".

### System Info (Optional)

OS: Windows 11 64 Bit

**Comment by Exzap** [comment]
This is by design if you run Cemu in the new non-portable mode which is the default for new installations. For more info see the [2.1 changelog](https://github.com/cemu-project/Cemu/releases/tag/v2.1) and #1252

The "Cemu dir" where the files need to be placed can easily be located by opening Cemu and selecting File -> Open Cemu folder
