### ISSUE TITLE
Extremely Insufferable Lag 

### ISSUE THREAD

**Issue by Moddedmyth** [cemu-project/Cemu#1342]
### Current Behavior

Certain games such as Breath of the wild and Mario 3d world suffer severe lagging issues that make them nearly unplayable.  Example: Going anywhere near Hyrule Castle in botw Causes a Devastating Frame drop.

### Expected Behavior

There should have been no frame drop in play, both games should launch well.

### Steps to Reproduce

Botw: Walk to Hyrule Castle and open to metal doors, after crossing the doors, unless in the air the game lags harshly 
SM3DW: Entering a train level makes the frame drop badly.

### System Info (Optional)

OS:
GPU:

**Comment by Exzap** [comment]
We can't really help if you provide no system info, no log, not even which operating system you are using. Cemu runs well for most people and if it doesn't, it's likely down to PC specs.
Anyway, in the future please use our discord or subreddit for basic troubleshooting questions like this. Github issues is more development focused and any question here takes time away from developers that would otherwise be spent on improving the software.
