### ISSUE TITLE
Native support for chromebooks

### ISSUE THREAD

**Issue by Caveproject** [cemu-project/Cemu#1374]
### Your suggestion

Hi, Is there a possibility to add Native support for Chromebooks (Powerful Chromebooks such as Chromebook plus). Cemu would be incredible to run on powerful chromebooks natively using something similar to borealis flag for steam or support for Chromebooks in Play store. Please let me know your thoughts. Thank You.

**Comment by ItsMaddieNow** [comment]
Doesn't borealis just run steam apps in a linux container, why not just download the appimage and run it in the already avaliable linux container.

**Comment by Caveproject** [comment]
Where is the appimage for Cemu?

**Comment by Caveproject** [comment]
Are Chromebooks supported?

**Comment by ItsMaddieNow** [comment]
The appimage is available for download on the github releases page that is linked on the cemu homepage.
All support you receive for cemu is voluntary and will likely be based on how much of a pain it will be to diagnose. With Chrome OS, it can be quite a pain because developers may not have the appropriate hardware, Chrome OS may impose restrictions on the Linux container that prevents devices like controllers from working and chrome os can be quite aggressive with killing resource intensive programs to prevent the system from locking up.
