### ISSUE TITLE
Add kaillera netplay support

### ISSUE THREAD

**Issue by mxsymeg** [cemu-project/Cemu#1394]
### Your suggestion

https://kaillerareborn.github.io/

Hopefully support for kaillera netplay can be added in subsequent releases!

**Comment by Squall-Leonhart** [comment]
Kaillera is a walking talking security vulnerability.

**Comment by Exzap** [comment]
There have been some internal discussions about netplay over the years, but the short answer is that it's just not viable for us due to the complexity of Wii U's architecture. It would come with a major performance decrease as it requires the entire emulator to run in a mostly single-threaded deterministic mode. It's also quite a mountain of work to implement it.

So at this point it's just not something that is planned and I recommend using an alternative like parsec instead.
