### ISSUE TITLE
Please use semantic versioning

### ISSUE THREAD

**Issue by Doomsdayrs** [cemu-project/Cemu#191]
`2.0-1` is a nonstandard way of saying `2.0.1`.

Reference: https://semver.org/

**Comment by Doomsdayrs** [comment]
This will also conflict with flatpak and it's auto updater functionality

**Comment by Exzap** [comment]
imho semver really only makes sense for libraries since it's defined in terms of API breakage. For end users a shorter number is easier to type and remember. That said, I'm not entirely happy with how we had to introduce an extra number for the experimental releases, but it's less of a version component and more of a running number for the sake of being able to distinguish individual builds that never resets. Dolphin does it like this too.

I'm closing this because it's been discussed many times before.

**Comment by jhmaster2000** [comment]
> This will also conflict with flatpak and it's auto updater functionality

Just to add onto what Exzap has said, a hyphen is NOT a nonstandard and it IS part of semver, read your own reference:
> 9. A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.–.

The only thing nonstandard about that version number (`2.0-1`) is the lack of a patch version which would be the last `.0` (`2.0.0-1`), which even though is not strictly standard, many semver parsers support it just fine as its very easy to "recover" from it by simply assuming the omitted patch version to be a zero, and translating it to a valid semver like so: `x.y` -> `x.y.0`.

See: https://github.com/semver/semver/issues/368

If flatpak doesn't support Cemu's versioning system due to either the missing patch number or the prerelease tag (hyphen syntax) then its up to them to fix it in their parser.
