### ISSUE TITLE
[Linux] [Radv vulkan driver] [BOTW] Tall grass like graphical bugs

### ISSUE THREAD

**Issue by Emerald-glitch** [cemu-project/Cemu#267]
Zelda: Breath of the wild has wierd texture issues with vulkan. It includes long grass like textues and some missing ones. 
![1](https://user-images.githubusercontent.com/84855747/190889970-50cd85c7-9105-4215-a4b7-896aebab9901.png)
![2](https://user-images.githubusercontent.com/84855747/190889984-c0d20234-1d20-407c-a798-083660873b54.png)

This is inside that grass texture

![3](https://user-images.githubusercontent.com/84855747/190889993-9102d6a3-bfa9-4650-a4d6-9e4e3df124cb.png)

same bug on building
![4](https://user-images.githubusercontent.com/84855747/190890030-f7648604-75c4-4f04-ac6e-f98a7d8e9369.png)

inside the above glitch
![5](https://user-images.githubusercontent.com/84855747/190890054-e3a4e256-a5de-4ecc-b230-ace89d0ae0b6.png)

some more 
![6](https://user-images.githubusercontent.com/84855747/190890064-a081a214-a9c0-4aee-a968-2119f5d195cb.png)

Oh and a opengl screenshot, it doesn't occur in opengl
![7](https://user-images.githubusercontent.com/84855747/190890078-c28ce9a5-6449-42f7-b864-1c697f4dc26f.png)

It is like this for me since forever really, the frequency of these tall grass has decreased though, in v1.26, it was way worse. I suspected bad dumb, but it works correctly with opengl, so i guess we can rule that out.

Anyway, I couldn't find anyone else with same problem that is also one of the reasons why i never posted about it.

I am using linux build with commit hash 
12b6830546e28e6a697c5dbcbc3aa24882ec7fb3

Artix linux 
Mesa version 22.1.7
vulkan version 1.3.211
opengl version 4.6
vulkan driver radv
cpu ryzen 3 3300u
gpu vega  6
ram 6 gb
vram 2gb

Oh and about log file, can someone give directions how to obtain them, i Have no idea how to.

**Comment by Squall-Leonhart** [comment]
if you don't follow the provided template, your issue will be closed

**Comment by goeiecool9999** [comment]
This is a known issue. It happens only on certain AMD GPU's using mesa. It started around the time some vulkan rewrite happened. It is suspected to be a synchronization issue.

**Comment by Emerald-glitch** [comment]
> 

i suspected it too, but i couldn't find any similar issue at all, hence the bug report, well since it is a known issue, should i close it?

> if you don't follow the provided template, your issue will be closed



> if you don't follow the provided template, your issue will be closed

**Comment by Emerald-glitch** [comment]
> if you don't follow the provided template, your issue will be closed

did i do something wrong, other than not providing the log file? Doesn't seem like it is necessary, since it is a known issue.

**Comment by Squall-Leonhart** [comment]
your bug was blank on first submission

**Comment by goeiecool9999** [comment]
Could you make the issue title more descriptive? e.g. show it only happens on linux and that it's a BotW problem.

**Comment by Emerald-glitch** [comment]
> Could you make the issue title more descriptive? e.g. show it only happens on linux and that it's a BotW problem.

How is this one?

**Comment by Cloudperry** [comment]
Yeah it *seems* that the bug happens only on Vega GPUs when using Vulkan. The bug has existed for a loong time when running Cemu through Wine and now its happening with the Linux native version as well. My GPU is a Vega 56.

It could be a driver bug and not a Cemu bug. I tested this on Arch Linux using RADV, AMDGPU-Pro Vulkan and AMDVLK. The only driver that didn't have this bug was AMDGPU-Pro. I tested using these packages: [vulkan-amdgpu-pro](https://aur.archlinux.org/packages/vulkan-amdgpu-pro), [vulkan-radeon](https://archlinux.org/packages/extra/x86_64/vulkan-radeon/) and [amdvlk](https://archlinux.org/packages/extra/x86_64/amdvlk/). I will edit this comment if there is a Mesa bug for this (or if I create one).

**Comment by goeiecool9999** [comment]
> Created a Mesa bug report

That's nice but I think I remember in the past the mesa developers were not very receptive to bug reports describing problems in cemu. I think at the time they cited that cemu was proprietary software and that they need a particular wii u game to reproduce the problem. One of those things has changed now but it's still a pretty big hurdle to acquire a Wii U and the game and learn how to dump games, just to test one issue on your issue tracker. I wouldn't be surprised if the only way this gets fixed is when someone finds the exact issue in cemu, whether it be a race condition that only shows on RADV for vega because of in-spec driver differences or a true driver bug.

**Comment by Cloudperry** [comment]
> they need a particular wii u game to reproduce the problem

That wouldn't be a problem if someone gets a trace/capture of the bug using [gfxreconstruct](https://github.com/LunarG/gfxreconstruct). I tried it using [this package](https://aur.archlinux.org/packages/gfxreconstruct-git), but couldn't make it work even after reading the desktop usage instructions on gfxreconstruct's github page.

If anyone gets gfxreconstruct working for Cemu pls tell me how u got it working. Or if u have a Vega GPU just post a capture in that Mesa bug report.

**Comment by Emerald-glitch** [comment]
> If anyone gets gfxreconstruct working for Cemu pls tell me how u got it working. Or if u have a Vega GPU just post a capture in that Mesa bug report.

I will try.

**Comment by Cloudperry** [comment]
Yep. I can confirm that it is fixed. Very nice to have this quite old bug dealt with. Surely this affected some other games as well right? 

Would be nice if all Vulkan drivers behaved the same way. I'm closing the Mesa bug report.
