### ISSUE TITLE
Option to open from CLI and not daemonize

### ISSUE THREAD

**Issue by hugochinchilla** [cemu-project/Cemu#326]
When using Cemu with a streaming solution like Steam, open-stream, sunshine, etc... I want to be able to run Cemu as a command and have the process attached to the terminal, so I can send a SigTerm to the terminal when I want to close the game. Currently I can open games from my TV but when I close the streaming session the game keeps running.

**Comment by goeiecool9999** [comment]
That's strange. I've never seen Cemu detach from the terminal and there's even some code that handles sigterm signals. Are you sure Cemu is daemonizing?

**Comment by BionicKnight** [comment]
Can you give a detailed step-to-step to replicate this behavior?

I ran a game using the command cemu -g path/to/game on terminal, and closed it 3 ways:
1. Clicking the close button, closed ok no process in backgroud etc.;
2. Ctrl + C, same as above;
3. Closed the terminal, cemu just closed together;

Then I ran it on Lutris, opened a game then closed click on close button
Lutris showed that the game was still running even if it really wasn't because of it's buggy process detection, checked task monitor, all closed
Which makes me think that maybe the software/service you used have some bug like this and then it's not really a Cemu problem.

(Sorry for my bad english or any typo, it's not my native language)

**Comment by hugochinchilla** [comment]
Sorry, I just realize I'm reporting a behavior on 1.26, this project is only for Cemu > 2.0 so maybe the behavior has changed, I will need to install Cemu 2 and test this behavior again.

**Comment by Exzap** [comment]
If this happens with 2.0 then feel free to open a new issue.
