### ISSUE TITLE
Feature Request: Bash Scripts to Clone Repo and Build x86_64 app on MacOS

### ISSUE THREAD

**Issue by GumbyXGames** [cemu-project/Cemu#336]
I wrote two bash scripts for to perform a "fresh" build (install x86_64 brew and dependencies to the correct paths, clone repo, and run cmake commands) and a update and build script. Thought they might be helpful to add to the repo:

Fresh_build.sh: [](https://pastebin.com/adfZsjsp)
Update_and_Build.sh: [](https://pastebin.com/Rh894mD)e

**Comment by Exzap** [comment]
Something went wrong because there is no script attached?

Anyway, I think the build instructions we have in [BUILD.md](https://github.com/cemu-project/Cemu/blob/main/BUILD.md) are pretty simple already. If you want to improve something in the instructions do it via PR instead of asking in an issue.
