### ISSUE TITLE
Cemu seems to be very allergic towards Mario Maker

### ISSUE THREAD

**Issue by Arcadius2006** [cemu-project/Cemu#363]
I don't think the game's supposed to look like this

i didn't get far enough into the game to unlock all the styles, so here's the two screenshots i have taken of the same course
![image](https://user-images.githubusercontent.com/93880348/195605904-cc5b452c-82c4-4ba8-98c8-67ce3b9aa29d.png)
![image](https://user-images.githubusercontent.com/93880348/195605960-dd24533f-470c-48ce-b93d-d27a62bd9040.png)

i don't think any comparisons are needed, as the issue should be quite obvious

**Comment by Arcadius2006** [comment]
almost forgot about the log and specs, sorry
Intel Pentium 3805U @1.90GHz
4GB ram
Nvidia GeForce 820M
[log.txt](https://github.com/cemu-project/Cemu/files/9776992/log.txt)

**Comment by Exzap** [comment]
That's a bug with older Nvidia drivers on OpenGL. See if you can update the graphics driver. If that's not possible you could try older Cemu releases as they have a workaround for this bug.

Anyway, closing this since the GPU is below minimum requirements and it's not feasible for us to support every piece of old hardware.
