### ISSUE TITLE
Boost error while compiling on KDE Neon

### ISSUE THREAD

**Issue by Blad3forc3** [cemu-project/Cemu#367]
Getting this error whilst compiling:

CMake Error at dependencies/vcpkg/scripts/buildsystems/vcpkg.cmake:826 (_find_package):
  Could not find a configuration file for package "boost_nowide" that exactly
  matches requested version "1.71.0".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/boost_nowide-1.76.0/boost_nowide-config.cmake, version: 1.76.0

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  build/vcpkg_installed/x64-linux/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
  dependencies/vcpkg/scripts/buildsystems/vcpkg.cmake:780 (include)
  CMakeLists.txt:92 (find_package)

I have boost 1.8.0 installed at /usr/include

I have read this on the howto:
If step 3 fails while compiling the boost-build dependency, it means you don't have a working/good standard library installation. Check the integrity of your system headers and making sure that C++ related packages are installed and intact.

They are installed correctly

**Comment by v-fox** [comment]
VCPKG is kind of a trap, it's a toolchain creation scripting monstrosity for Windows systems that don't have proper package manager that does more harm than good in Linux. It's much simpler to disable it with `-DENABLE_VCPKG=OFF -DPORTABLE=OFF` and also add `-DVCPKG_USE_SYSTEM_BINARIES=ON -DVCPKG_PREFER_SYSTEM_LIBS=ON` to make sure that it doesn't try something anyway, then get all cemu dependencies into the system properly. But you better off distro's dedicated packaging build-servers, unless you use Gentoo or Arch, or ask maintainers to make packages for you if you don't want to learn to become one through a lot of trials and errors.

But in your case there is whole bunch of inconsistencies, such as 1) you don't have something installed into /usr/include because it's only for headers, there are also libraries and packager files (pkg/cmake, etc.) 2) your log says that you have "1.76.0" installed but you claim "1.8.0" (which would be ancient). I successfully used 1.80.0.

**Comment by Blad3forc3** [comment]
Thanks for the response it has helped. I now get this error even though i have glslang-dev installed:

CMake Error at CMakeLists.txt:94 (find_package):
  By not providing "Findglslang.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "glslang", but
  CMake did not find one.

  Could not find a package configuration file provided by "glslang" with any
  of the following names:

    glslangConfig.cmake
    glslang-config.cmake

  Add the installation prefix of "glslang" to CMAKE_PREFIX_PATH or set
  "glslang_DIR" to a directory containing one of the above files.  If
  "glslang" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by v-fox** [comment]
> Thanks for the response it has helped. I now get this error even though i have glslang-dev installed:

Check out [my spec-file](https://build.opensuse.org/package/show/home:X0F:branches:Emulators/cemu) for making a package on a build-server. You can see exact dependency versions (11.11.0 for glslang, as of now) in the build-log accessible from the right (although it may ask for registration to access).

There might be another problem that causes it to treat glslang as missing such as absence of glslang's dependencies which, normally, should be pulled too, lack of cmake-files or their corruption/inconsistency. For example, openSUSE manually [changes some lines in glslang](https://build.opensuse.org/package/show/X11:Wayland/glslang)'s cmake-files and patches its crappy library versioning (or lack thereof).

**Comment by Exzap** [comment]
Closing this because it seems stale. In the future please use the Discord for compilation troubleshooting.
