### ISSUE TITLE
Twilight Princess HD - L & ZL don't work on Steam Deck

### ISSUE THREAD

**Issue by undeadindustries** [cemu-project/Cemu#379]
On the SteamDeck with EmuDeck and Batocera, the L and ZL buttons do not work in Twilight Princess HD.

Steps to reproduce:
-Install EmuDeck or use Batocera, keys.txt and Twilight Princess HD
-In EmuDeck, choose the Cemu controller profile
-Launch Twilight Princess HD and play until you get the fishing pole (like 5 minutes). You are then instructed to equip the fishing pole with L. L and ZL do nothing. (This works fine in the Gamecube version in Dolphin)

Other details:
-This happens in 1.26 and 1.27 (don't have hashes. It's whatever EmuDeck or Batocera allow by default)
-Switching to different steam controller profiles and remapping controller buttons doesn't help
-Switching to OpenGL doesn't fix it. Also OpenGL would be too slow on SteamDeck anyways...
-L and ZL work in other games and emulators.
-Tried a few different ISOs.

Please let me know if there's anything else I can do to help sort this out.

Thank you!

**Comment by Squall-Leonhart** [comment]
Emudecks fault, take it up with them.

**Comment by Exzap** [comment]
First of all, we can't provide any kind of support for those that admit to piracy ("Tried a few different ISOs") even if the issue is legitimate. We don't accept bug reports for 1.26 and 1.27 anymore either as they are outdated releases. 
But most likely there isn't even a bug here, the fishing controls are just notoriously unintuitive and got changed with the HD release. I don't have them memorized but I don't think there is Z/ZL involved at all, at least when using the GamePad.
