### ISSUE TITLE
[Linux] Wiimote through SDLController only partially works

### ISSUE THREAD

**Issue by lisa-wolfgang** [cemu-project/Cemu#443]
When adding a Wiimote using the SDLController API (the Wiimote API doesn't show as an option on Linux), multiple options appear. Across all of these options, only the A, B, and HOME buttons (on the Wiimote) and the C and Z buttons (on the Nunchuk) are recognized by Cemu. None of the other buttons on the physical remote are able to be registered to a mapping option:
![image](https://user-images.githubusercontent.com/43426138/199380686-7a32310c-badd-44d3-80cb-24cf3bbff663.png)

When configuring the controller that gave the A/B/HOME inputs, rumble functions as intended, but the motion option is greyed out.

Cemu version: https://github.com/cemu-project/Cemu/commit/c3182aedd9895cd8cde0d02440a22bd5a060b7d4
Operating system: Ubuntu 22.04.1 LTS

**Comment by Squall-Leonhart** [comment]
SDL is not remappable, the mapping screen only reflects the settings of API's that are, so nothing you see set there, or not set there is an indication that the controller isn't fully mapped.

**Comment by lisa-wolfgang** [comment]
Sorry, I didn't explain the issue very clearly, so I've gone back and made a couple of edits. That screenshot was meant to illustrate the only buttons I was able to get working.

**Comment by Squall-Leonhart** [comment]
Issues with the SDL mapping are to be addressed to the SDL developers, they maintain the controller profiles upstream.

**Comment by lisa-wolfgang** [comment]
Upon further investigation, SDL seems to work fine as far as detecting input -- the problem is that Cemu doesn't seem to be able to read the inputs properly.

Source 0 (the Wii Remote's buttons) has 12 functional buttons, but Cemu only recognizes 3 of them.
Source 1 (the Wii Remote's Accelerometer) has 3 functional axes, but Cemu doesn't recognize any of them, and the motion option is greyed out for this source.
I wasn't able to test Source 2 (the Wii Remote's IR sensor) as I do not have an IR source to test with.

The order of the following sources seems to be a race condition between when the extensions are detected. In my testing, MotionPlus (built-in on my remote) has come after the Nunchuk occasionally.
Source 3 (MotionPlus) has 3 functional axes, but Cemu doesn't recognize any of them. The motion option is greyed out for this source. I'm not sure how to test if the MotionPlus checkbox has any effect.
Source 4 (Nunchuk if plugged in) has 3 functional axes, 2 functional buttons, and 1 "hat", but Cemu only recognizes the 2 buttons. The motion option is greyed out for this source.

Cemu only seems to be following the `Name` and `Mapping` properties of `GameController` rather than each individual joystick/source. Besides not being able to read all available inputs, it's not ideal user experience to have 5 indistinguishable sources that each do something different:

![image](https://user-images.githubusercontent.com/43426138/199563295-95e88991-45e9-41b9-a6fe-3c9cbfcf9f23.png)

**Comment by lisa-wolfgang** [comment]
It does appear that better Wiimote support in general has been added to the development branch of SDL (starting at https://github.com/libsdl-org/SDL/commit/c72e14e8f496363d76d3ba1743ec54391b7e30e2), but this won't come to a release version for another month or two, and then this new version needs to be picked up by distros.

**Comment by v1993** [comment]
Coming from person who spent a LOT of time messing with SDL and WiiMotes in the past...

1. SDL itself is more than capable of reading all button presses coming from wiimote. It's just that Cemu decides to use controller API that's a poor fit for less standard controllers. This can be worked around by using remapping tool such as https://generalarcade.com/gamepadtool/.
2. Wiimote's motion is a story on its own on Linux... It was added way before standard API for motion devices became available and SDL currently does not even support said standard API.
3. Linked commit in SDL adds HIDAPI driver that is disabled by default on Linux due to its shortcomings.

I'd say that for now the easiest way to use wiiremote in cemu is https://github.com/v1993/linuxmotehook2 (by me). It includes support for motion as well.

**Comment by matthew-js-porter** [comment]
@v1993 Does that work with IR pointing too?

**Comment by v1993** [comment]
Sadly no, since this is not something underlying protocol supports. It wouldn't work with SDL either tho.

**Comment by robertswiecki** [comment]
Does [linuxmotehook2](https://github.com/v1993/linuxmotehook2) work correctly for you?

I made it to work with dolphin, but with cemu I get strange results for motion - it works correctly with eg Mario Kart 8 - if I turn the wiimote, so it points buttons towards the TV. Otherwise the axies seem kinda reversed.

I know that it's possible to reverse it in the config, but since it works well with dolphin...

**Comment by v1993** [comment]
@robertswiecki It's been forever since I've last used Cemu, so, sadly, there isn't much for me to say here. See https://github.com/v1993/linuxmotehook2/issues/9 for the same problem.

> PS: When I tried just now, the results were differnt, I was able to play the game if I pointed the buttons side of the Wiimote (Wiimote Plus - the -TR version) towards the floor.

Sounds like Cemu now applies orientation transformation on its own, huh? I'm not following its development, but that sounds plausible. I wonder if there's at least an option to turn that off.

**Comment by GNUGradyn** [comment]
This is still an issue. As far as I'm aware, there is no way to get full wiimote support on linux. For example, you can't add accelerometer controls via SDL. This is a showstopper for even basic games like super mario bros U. On windows, it seems you can pass wiimotes through directly via the "Wiimote" option under API. This is not an option on linux. Even running CEMU via proton does not resolve this issue because the emulator in proton cannot see any bluetooth devices connected to the host.

**Comment by lisa-wolfgang** [comment]
@GNUGradyn https://github.com/v1993/linuxmotehook2 is a full solution. It is true that Cemu doesn't have a built-in full solution on Linux, though.

**Comment by lisa-wolfgang** [comment]
Closing since the native Wiimote API is now available on Linux and should be used instead of SDLController.
