### ISSUE TITLE
Allow pure build

### ISSUE THREAD

**Issue by rowanG077** [cemu-project/Cemu#57]
Hello everyone,

First of I want to thank the Cemu team for open sourcing the emulator. I have been literally waiting for this for years.

The first thing I wanted to do is start packaging it for the distribution I use so everyone can enjoy it! But I quickly ran into issue while trying to build Cemu. I installed all deps listed in the build guide but it seems Cemu tries to install additional dependencies, such as vcpkg.

The distro I use requires a pure build so it's not possible to fetch and install dependencies at build time. So my request is to allow all dependencies to be specified up front. Allowing a transparent and reproducible  build process to be specified for distros.

**Comment by strikersix23** [comment]
I would agree this would allow easier porting for Linux derivatives that vcpkg does not support

**Comment by Tatsh** [comment]
All distros generally require offline builds. You can use vcpkg with the `--no-downloads` option.

But also, I am working on making this work on Gentoo without needing vcpkg or live downloading of any kind. The patch set is not totally organised yet.

The other issue is that vcpkg pulls in the latest version of everything by default. The version of wxGTK+ on Gentoo is quite a bit dated by comparison, but this is normal because that version of wxWidgets is very new and not considered stable.

Anyway, this should be tracked in #1. Let's not open so many issues about build issues on Linux.
