### ISSUE TITLE
[Feature Request] Extract a .WUA file : one at one or in bulk

### ISSUE THREAD

**Issue by ghost** [cemu-project/Cemu#713]
Add in the context menu of the title manager window an option to extract a .WUA file. 

A stand alone tool to compress and extract a .WUA / .ZAR file already exist ([ZArchive](https://github.com/Exzap/ZArchive)). 

This can be very useful and convenient to have an extract tool intergrated to Cemu.

Also, this can be convenient to be able to extract in bulk multiple titles in the same time or only one title at the time.

**Comment by Squall-Leonhart** [comment]
Duplicate #568 

You can't.

**Comment by mx00010** [comment]
Thanks to link this ticket to the original request. As per the #568, that's not possible to retreive a full quality archive file and this make a lot of sense due to the fact that datas to do this have been loss somewhere in the process to create the compressed file.

So it's a little brainstorming here and maybe this can help to reduce the feature scope, Based on the fact above, if this feature primary focus only on a one way to extract from .WUA to folders and the user expectations are managed with a warning message or something like that before the extract process, is this something more realistic or still not.

**Comment by Exzap** [comment]
#568 is unrelated to this request. But I added [some context](https://github.com/cemu-project/Cemu/issues/568#issuecomment-1484072558) there because of the whole "Is WUA lossy?" confusion (It's not. The problem lies elsewhere)

I think rather than having an explicit "WUA extractor" in Cemu it would make more sense to have a general extractor tool that works with every input format (.wud, .wux, .wua). Bulk conversions would be nice but it's imho out of the scope considering Cemu is an emulator.

**Comment by mx00010** [comment]
To continue this brainstorming, I agree, a general tool to manage every input format can be very nice (and thanks about the clarification if WUA format is lossless or not).

But on the other hand, if we focus exclusively on CEMU features, a ".wux/.wud --> .wua" and a "folders --> .wua" already exist as a feature in the title manager window (and this one is very usefull). In this way, this can make sense to the users to be able to reverse back the process with a simple ".wua --> folders" extract process (but nothing fancy as a general extractor tool as discussed above).

Also, a little bit thinking about thinking, but if we push a little bit more this thing : during a ".wux/.wud --> .wua" process, the files contained in the .wud/.wux need to be extracted before .wua conversion. So this functionality should be already somewhere in the code (currently maybe not exposed to the final users). So, can we asume there's no big steps to also benefit of a ".wux/.wud --> folders" extraction process in the same time.
