### ISSUE TITLE
[2.0] Missing games in list

### ISSUE THREAD

**Issue by FrankAlbella** [cemu-project/Cemu#757]
Verison: 2.0-32 (appimage)
Operating System: Pop!_OS 22.04
Issue: Games that are detected when running Cemu 1.26.2f are not detected when the same directory is selected on the latest version (2.0-32). 

The games most of the games that don't show up in the 2.0-32 are ones where the update was merged with the game data, but these show up as a red entry in the 1.26.2f version. Super Smash Bros., however, does not show up as a red entry and yet still does not appear in the appimage version.

The list of games that don't show up is as follows:
Red entries: Mario Kart 8, Super Mario Maker, The Legend of Zelda: Twilight Princess
Normal entries: Super Smash Bros. - for Wii U

2.0-32 (appimage):
![image](https://user-images.githubusercontent.com/3748949/230774160-6567858c-eca1-4505-9913-11d6a61524e5.png)

1.26.2f (through wine):
![image](https://user-images.githubusercontent.com/3748949/230774219-44cbd737-a09f-4b40-a132-bc6904833fa5.png)

**Comment by Exzap** [comment]
This is similar to #437.

Since 1.27.0 we no longer show titles with broken meta data (e.g. when merging updates into the base game). This change was necessary because we now support loading updates and dlc from the game folder and for that to work we have to rely on the meta data being intact. Redump your games and dont manually merge them and it will be fine.

**Comment by Squall-Leonhart** [comment]
And make use of WUA, as this is also a means of reducing disk footprint.
