### ISSUE TITLE
[Feature Request] Vulkan can now be used without pipelines.

### ISSUE THREAD

**Issue by PunchCakee** [cemu-project/Cemu#759]
The Khronos group has announce that vulkan can now be used without pipelines.

[Here is the announcement link.](https://www.khronos.org/blog/you-can-use-vulkan-without-pipelines-today)

I think implementing it would reduce loading times but i am quite unsure of how difficult it is to implement since i am unexperienced with vulkan.

**Comment by Exzap** [comment]
`VK_EXT_shader_object`'s main focus is on programmer convenience and getting rid of some of Vulkan's "staticness" that makes it hard to work with. But since we already went through the effort and implemented everything using pipelines and renderpasses it's a bit too late for us :)

The gist of the extension is that they replaced pipelines with shader objects and dynamic state, in essence going back to the OpenGL model. It won't cut down on compilation time because compilation still needs to happen for the shader objects (they can't magic compilation away). Although they do provide new ways to reduce compilation times, e.g. using separable shaders, but those can't really be leveraged in our case.

Lastly, only Nvidia has a beta driver for this so far and we don't know how performance will look in practice. I doubt that it will be faster by a significant enough margin anytime soon, if ever.

>  i am quite unsure of how difficult it is to implement since i am unexperienced with vulkan.

It's a fundamental shift in how things work. It would require large scale changes almost like writing a new backend.
