### ISSUE TITLE
[Discussion] Should being packaged by Linux distributions be a supported use-case?

### ISSUE THREAD

**Issue by ReillyBrogan** [cemu-project/Cemu#78]
Following on from my comments in #74 I'd like to bring the question of whether or not Cemu being packaged by Linux distributions should be a supported use-case? Or should the focus be on providing "official" builds (via Flatpak, AppImage, or just a self-contained archive)? 

Benefits of allowing distribution packages:
- Users can install Cemu via the same mechanism they use to install the majority of the packages they use (*)
- Users can use system libraries that are more optimized for the specific distribution (this is always touted as a major con by people who support trying to package every application under the sun, but in practice there is very little value in this from the perspective of the users and the application developers). 

Cons:
- Increased number of bug reports from users using system packaged Cemu due to different versions of dependencies in use and/or differences in the build environment (such as default CFLAGS/LDFLAGS)
- Increased time spent triaging issues that are reported (what Cemu version is in use, what libraries is it using, etc)
- Users must wait until the package is updated by their maintainer for any Cemu fixes (which may be delayed by dependency mismatches, maintainer availability etc).
- Increased complexity of code due to having to maintain compatibility with several dependency versions at once 
- Rolling back Cemu may be difficult/impossible due to dependency mismatch

Ultimately distribution packages are going to lead to an increase in the number of user issues for various reasons with a corresponding decrease in the ability of Cemu developers to help (for instance what is the Cemu dev/user supposed to do when the issue exists in library version a.b.c when version a.b.d is out but the distribution has not yet updated to it?).

* I note that many (most?) distributions support Flatpak now and that so long as the distribution is not using a custom software center Flatpak support is likely to be directly integrated such that Flatpaks can be installed and managed that way. In that situation installing Flatpaks can be just as seamless as system packages.

Benefits of NOT supporting distribution packages and only supporting release binaries:
- Releases have the exact dependencies that the release was developed against. E.g every user of version 2.4 has the exact same set of dependencies as every other user.
- Cemu can integrate an auto-update mechanism. For instance allowing users to check for updates and install them from within Cemu itself.
- Users can downgrade to old versions as needed without otherwise affecting their systems (for instance if there's a regression on a particular game with the new version).
- Users still have a good experience with Cemu even if they're on a "stable" distribution which doesn't do major version updates for existing packages.
- Reduced code complexity due to only needing to support a certain set of application dependencies at once.

Cons:
- App isolation technologies like Flatpak and AppImage can have issues fully integrating with the rest of the system (such as GTK themes, fonts)
- Refusing to support system packages tends to be negatively received by a certain subset of "purist" Linux users. These users very much tend to be far more vocal than other users which can make it seem like this group is larger than it actually is. (Most users are more pragmatic and/or simply don't care about how the application is delivered to them, they are just happy to have Cemu working on Linux as is).

I would like to note that I am an objective observer here, without any real feelings on which option is best for Cemu. I do a fair amount of work on system packaging including complex applications like Cemu and so see a lot of this first-hand. Many applications are simply ill-suited for being available in distribution package repos and trying to shoehorn them in often leads to grief that could have been avoided if application developers had simply realized that allowing packaging was a bad decision from the beginning. I see individuals like @Tachi107 either implicitly or explicitly working on various initiatives to pave the way for system packaging and I worry that @Exzap, being as far as I can tell generally unfamiliar with Linux and it's community except for the work involved in the initial porting, may not have realized the full implications of much of this. Allowing and supporting system packages WILL be opening a can of worms when the needs of the Linux community could just as well be served by providing high quality binary distributions of Cemu.

**Comment by Tachi107** [comment]
> Benefits of allowing distribution packages:
> 
>  * Users can install Cemu via the same mechanism they use to install the majority of the packages they use (*)
> 
>  * Users can use system libraries that are more optimized for the specific distribution (this is always touted as a major con by people who support trying to package every application under the sun, but in practice there is very little value in this from the perspective of the users and the application developers).

I'd like to add that by developing stuff in a distro-friendly way, users who want to build Cemu from source will have less issues in doing so, as the build system would already have checks in place to reject unsupported dependencies (using versioned `find_package()` calls would help a lot, just take a look at the mess in issue #1).

Also, distro packagers are often skilled people who have worked and helped a lot of different upstream projects, and letting them do their stuff would lead to collaboration with upstream and downstream, ultimately improving code quality. This is one of the benefits of open source in general.

> Cons:
> 
>  * Increased number of bug reports from users using system packaged Cemu due to different versions of dependencies in use and/or differences in the build environment (such as default CFLAGS/LDFLAGS)

Poorly developed distro packages shouldn't be distributed in the first place... Different versions of the same dependency do not cause issues if Cemu is compatible with them, and if it is not then CMake would refuse to build.

Debian is sometimes known for shipping heavily altered packages that cause issues to end users, and I deeply dislike this manner of packaging stuff. I always try to stay as close to upstream as possible in order to minimize breakings

>  * Increased time spent triaging issues that are reported (what Cemu version is in use, what libraries is it using, etc)

Yes, but they would have to ask about the Cemu version and distro anyway, sometimes issues manifest on certain platforms independently of the packaging format.

>  * Users must wait until the package is updated by their maintainer for any Cemu fixes (which may be delayed by dependency mismatches, maintainer availability etc).

This is not a downside of supporting distro packaging. This is a downside of _using_ distro packages.

>  * Increased complexity of code due to having to maintain compatibility with several dependency versions at once

No, they don't necessarily have to. For example, if they only want to support e.g. fmt 8, they can. Distros will simply have a harder time packaging the software. And if they want to, maintainers can submit patches improving the situation.

>  * Rolling back Cemu may be difficult/impossible due to dependency mismatch

This is not a downside of supporting distro packaging. This is a downside of _using_ distro packages.

>  * I note that many (most?) distributions support Flatpak now and that so long as the distribution is not using a custom software center Flatpak support is likely to be directly integrated such that Flatpaks can be installed and managed that way. In that situation installing Flatpaks can be just as seamless as system packages.

Using one does not exclude the other.

> Benefits of NOT supporting distribution packages and only supporting release binaries:
> 
>  * Releases have the exact dependencies that the release was developed against. E.g every user of version 2.4 has the exact same set of dependencies as every other user.

True,

>  * Cemu can integrate an auto-update mechanism. For instance allowing users to check for updates and install them from within Cemu itself.

Cemu can do this regardless; distros would patch it out.

>  * Users can downgrade to old versions as needed without otherwise affecting their systems (for instance if there's a regression on a particular game with the new version).

This is not a downside of supporting distro packaging. This is a downside of _using_ distro packages.

>  * Users still have a good experience with Cemu even if they're on a "stable" distribution which doesn't do major version updates for existing packages.

This is not a downside of supporting distro packaging. This is a downside of _using_ distro packages.

>  * Reduced code complexity due to only needing to support a certain set of application dependencies at once.

I think you've repeated yourself.

> Cons:
> 
>  * App isolation technologies like Flatpak and AppImage can have issues fully integrating with the rest of the system (such as GTK themes, fonts)

True.

>  * Refusing to support system packages tends to be negatively received by a certain subset of "purist" Linux users. These users very much tend to be far more vocal than other users which can make it seem like this group is larger than it actually is. (Most users are more pragmatic and/or simply don't care about how the application is delivered to them, they are just happy to have Cemu working on Linux as is).

Purists suck. Don't even consider them.

**Comment by Exzap** [comment]
It's just not our current priority. We can look into supporting building for distro packages in the long term but for now our effort should be directed towards flatpak and appimage as the official way of distribution as that's in line with what most users want.

**Comment by Tachi107** [comment]
Note that you don't have to actively "support" packages, it's just a matter of accepting pull requests like #75...
