### ISSUE TITLE
Input profile doesn't save/restore settings properly

### ISSUE THREAD

**Issue by obsttaxi** [cemu-project/Cemu#85]
Cemu 2.0

When you create a new Profil for example with Buttonlayout AABBXXYY, and then another Profil with Buttonlayout ABBAXYYX, it will be saved but not load correctly.

[https://youtu.be/E_UnH8MtrkA](https://youtu.be/E_UnH8MtrkA)

**Comment by Darkhost1999** [comment]
Testing 2.0-5 clicking to load an input profile does in fact load it. Everything under the hood works fine. But visually the UI doesn't refresh. So in order to "load" the controller profile you need to click load. Then close the window and open it again to see the changes.
This should aid in those fixing the issue it's just cosmetic not functionality.

**Comment by thanone2** [comment]
the true problem is that when I start a game the profiles aren't saved correctly then when I remap the controls it doesn't care and continues using the incorrect layout.
