### ISSUE TITLE
Cemu Online Functionality Not Working on Linux, but Working on Windows

### ISSUE THREAD

**Issue by PaperTobi** [cemu-project/Cemu#989]
Description:

Problem:
The online functionality of Cemu does not work on Linux, although it runs on Windows. I have made several attempts to resolve the issue, but so far, without success.

Operating System: Linux [Flatpak version]

Expected Behavior:
The online functionality should work the same way on Linux as it does on Windows. Online features should be accessible without issues.

Please fix!

**Comment by amppz** [comment]
Are you sure you put your files in the right location?

**Comment by PaperTobi** [comment]
Yes, I tried it the same way on Linux like I tried it on Windows. Windows accepts the keys in the settings, Linux doesn't

**Comment by amppz** [comment]
Keys??

**Comment by PaperTobi** [comment]
The online files.

**Comment by amppz** [comment]
Most of the files should be in your mlc, and `seeprom.bin` and `otp.bin` belong in `~/.var/app/info.cemu.Cemu/data/Cemu`

**Comment by PaperTobi** [comment]
I just said I already did. I just tried the Windows version with wine, the files get detected. Only the flatpak version doesn't work.

**Comment by PaperTobi** [comment]
Hello?

**Comment by flotwig** [comment]
@PaperTobi I'm having the same issue. After using [`strace` to see what files were accessed](https://superuser.com/a/1686669/458816), I see that Cemu is only looking in `~/.local/share/Cemu` for `seeprom.bin` and `otp.bin`, not the actual Cemu install dir. Strangely, the `mlc01` file lookups DO use the actual Cemu install dir: 

```
newfstatat(AT_FDCWD, "/home/flotwig/.local/share/Cemu/otp.bin", 0x7ffd90faf8f0, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/home/flotwig/.local/share/Cemu/seeprom.bin", 0x7ffd90faf8f0, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/var/opt/Cemu/mlc01/sys/title/0005001b/10054000/content/ccerts/WIIU_COMMON_1_RSA_KEY.aes", {st_mode=S_IFREG|0644, st_size=1200, ...}, 0) = 0
newfstatat(AT_FDCWD, "/var/opt/Cemu/mlc01/sys/title/0005001b/10054000/content/ccerts/WIIU_COMMON_1_RSA_KEY.aes", {st_mode=S_IFREG|0644, st_size=1200, ...}, 0) = 0
newfstatat(AT_FDCWD, "/var/opt/Cemu/mlc01/sys/title/0005001b/10054000/content/ccerts/WIIU_ACCOUNT_1_RSA_KEY.aes", {st_mode=S_IFREG|0644, st_size=1200, ...}, 0) = 0
newfstatat(AT_FDCWD, "/var/opt/Cemu/mlc01/sys/title/0005001b/10054000/content/ccerts/WIIU_ACCOUNT_1_RSA_KEY.aes", {st_mode=S_IFREG|0644, st_size=1200, ...}, 0) = 0
newfstatat(AT_FDCWD, "/var/opt/Cemu/mlc01/sys/title/0005001b/10054000/content/ccerts/WIIU_OLIVE_1_RSA_KEY.aes", {st_mode=S_IFREG|0644, st_size=1200, ...}, 0) = 0
```

Looks like a bug here, since it doesn't work as documented in the Online Play docs or the error message ("x.bin missing in Cemu root directory"). As a workaround, put your 2 `.bin` files in `~/.local/share/Cemu` instead of the Cemu root directory.

**Comment by Exzap** [comment]
I don't think there is a bug, more a confusion where the files go. Which is understandable because the guide and error messages are still mostly Windows specific.
Anyway, in Cemu's menu you can now click `file -> Open Cemu folder` and it should open the directory where `otp.bin` and `seeprom.bin` need to be placed.

**Comment by flotwig** [comment]
@Exzap the bug (maybe just a defect) is that the in-app error message on Linux is incorrect and gives the wrong directory in the resolution instructions
